var places = [
	{c: 12, r: 0, colour: 'red', type: 'home', pos: 4, occupied: 'red'},
	{c: 60, r: 0, colour: 'blue', type: 'home', pos: 1, occupied: 'blue'},
	{c: 22, r: 1, colour: 'red', type:'', pos: 2, occupied: ''},
	{c: 29, r: 1, colour: 'white', type:'', pos: 3, occupied: ''},
	{c: 36, r: 1, colour: 'white', type:'', pos: 4, occupied: ''},
	{c: 43, r: 1, colour: 'white', type:'', pos: 5, occupied: ''},
	{c: 50, r: 1, colour: 'blue', type:'', pos: 6, occupied: ''},
	{c: 8, r: 2, colour: 'red', type:'home', pos: 3, occupied: 'red'},
	{c: 64, r: 2, colour: 'blue', type:'home', pos: 2, occupied: 'blue'},
	{c: 4, r: 4, colour: 'red', type:'home', pos: 2, occupied: 'red'},
	{c: 16, r: 4, colour: 'red', type:'', pos: 1, occupied: ''},
	{c: 56, r: 4, colour: 'blue', type:'', pos: 7, occupied: ''},
	{c: 68, r: 4, colour: 'blue', type:'home', pos: 3, occupied: 'blue'},
	{c: 0, r: 6, colour: 'red', type:'home', pos: 1, occupied: 'red'},
	{c: 72, r: 6, colour: 'blue', type:'home', pos: 4, occupied: 'blue'},
	{c: 10, r: 7, colour: 'red', type:'', pos: 28, occupied: ''},
	{c: 17, r: 7, colour: 'red', type:'final', pos: 1, occupied: ''},
	{c: 55, r: 7, colour: 'blue', type:'final', pos: 1, occupied: ''},
	{c: 62, r: 7, colour: 'blue', type:'', pos: 8, occupied: ''},
	{c: 22, r: 9, colour: 'red', type:'final', pos: 2, occupied: ''},
	{c: 50, r: 9, colour: 'blue', type:'final', pos: 2, occupied: ''},
	{c: 4, r: 10, colour: 'red', type:'', pos: 27, occupied: ''},
	{c: 68, r: 10, colour: 'blue', type:'', pos: 9, occupied: ''},
	{c: 27, r: 11, colour: 'red', type:'final', pos: 3, occupied: ''},
	{c: 45, r: 11, colour: 'blue', type:'final', pos: 3, occupied: ''},
	{c: 4, r: 13, colour: 'white', type:'', pos: 26, occupied: ''},
	{c: 32, r: 13, colour: 'red', type:'final', pos: 4, occupied: ''},
	{c: 40, r: 13, colour: 'blue', type:'final', pos: 4, occupied: ''},
	{c: 68, r: 13, colour: 'white', type:'', pos: 10, occupied: ''},
	{c: 4, r: 16, colour: 'white', type:'', pos: 25, occupied: ''},
	{c: 68, r: 16, colour: 'white', type:'', pos: 11, occupied: ''},
	{c: 4, r: 19, colour: 'white', type:'', pos: 24, occupied: ''},
	{c: 32, r: 19, colour: 'green', type:'final', pos: 4, occupied: ''},
	{c: 40, r: 19, colour: 'yellow', type:'final', pos: 4, occupied: ''},
	{c: 68, r: 19, colour: 'white', type:'', pos: 12, occupied: ''},
	{c: 27, r: 21, colour: 'green', type:'final', pos: 3, occupied: ''},
	{c: 45, r: 21, colour: 'yellow', type:'final', pos: 3, occupied: ''},
	{c: 4, r: 22, colour: 'green', type:'', pos: 23, occupied: ''},
	{c: 68, r: 22, colour: 'yellow', type:'', pos: 13, occupied: ''},
	{c: 22, r: 23, colour: 'green', type:'final', pos: 2, occupied: ''},
	{c: 50, r: 23, colour: 'yellow', type:'final', pos: 2, occupied: ''},
	{c: 10, r: 25, colour: 'green', type:'', pos: 22, occupied: ''},
	{c: 17, r: 25, colour: 'green', type:'final', pos: 1, occupied: ''},
	{c: 55, r: 25, colour: 'yellow', type:'final', pos: 1, occupied: ''},
	{c: 62, r: 25, colour: 'yellow', type:'', pos: 14, occupied: ''},
	{c: 0, r: 26, colour: 'green', type:'home', pos: 4, occupied: 'green'},
	{c: 72, r: 26, colour: 'yellow', type:'home', pos: 1, occupied: 'yellow'},
	{c: 4, r: 28, colour: 'green', type:'home', pos: 3, occupied: 'green'},
	{c: 16, r: 28, colour: 'green', type:'', pos: 21, occupied: ''},
	{c: 56, r: 28, colour: 'yellow', type:'', pos: 15, occupied: ''},
	{c: 68, r: 28, colour: 'yellow', type:'home', pos: 2, occupied: 'yellow'},
	{c: 8, r: 30, colour: 'green', type:'home', pos: 2, occupied: 'green'},
	{c: 64, r: 30, colour: 'yellow', type:'home', pos: 3, occupied: 'yellow'},
	{c: 22, r: 31, colour: 'green', type:'', pos: 20, occupied: ''},
	{c: 29, r: 31, colour: 'white', type:'', pos: 19, occupied: ''},
	{c: 36, r: 31, colour: 'white', type:'', pos: 18, occupied: ''},
	{c: 43, r: 31, colour: 'white', type:'', pos: 17, occupied: ''},
	{c: 50, r: 31, colour: 'yellow', type:'', pos: 16, occupied: ''},
	{c: 12, r: 32, colour: 'green', type:'home', pos: 1, occupied: 'green'},
	{c: 60, r: 32, colour: 'yellow', type:'home', pos: 4, occupied: 'yellow'}
];

export {places};