var places = [
	{c: 12, r: 0, colour: 'red', type: 'home', pos: 4},
	{c: 60, r: 0, colour: 'blue', type: 'home', pos: 1},
	{c: 22, r: 1, colour: 'red', type:'', pos: 2},
	{c: 29, r: 1, colour: 'white', type:'', pos: 3},
	{c: 36, r: 1, colour: 'white', type:'', pos: 4},
	{c: 43, r: 1, colour: 'white', type:'', pos: 5},
	{c: 50, r: 1, colour: 'blue', type:'', pos: 6},
	{c: 8, r: 2, colour: 'red', type:'home', pos: 3},
	{c: 64, r: 2, colour: 'blue', type:'home', pos: 2},
	{c: 4, r: 4, colour: 'red', type:'home', pos: 2},
	{c: 16, r: 4, colour: 'red', type:'', pos: 1},
	{c: 56, r: 4, colour: 'blue', type:'', pos: 7},
	{c: 68, r: 4, colour: 'blue', type:'home', pos: 3},
	{c: 0, r: 6, colour: 'red', type:'home', pos: 1},
	{c: 72, r: 6, colour: 'blue', type:'home', pos: 4},
	{c: 10, r: 7, colour: 'red', type:'', pos: 28},
	{c: 17, r: 7, colour: 'red', type:'final', pos: 1},
	{c: 55, r: 7, colour: 'blue', type:'final', pos: 1},
	{c: 62, r: 7, colour: 'blue', type:'', pos: 8},
	{c: 22, r: 9, colour: 'red', type:'final', pos: 2},
	{c: 50, r: 9, colour: 'blue', type:'final', pos: 2},
	{c: 4, r: 10, colour: 'red', type:'', pos: 27},
	{c: 68, r: 10, colour: 'blue', type:'', pos: 9},
	{c: 27, r: 11, colour: 'red', type:'final', pos: 3},
	{c: 45, r: 11, colour: 'blue', type:'final', pos: 3},
	{c: 4, r: 13, colour: 'white', type:'', pos: 25},
	{c: 32, r: 13, colour: 'red', type:'final', pos: 4},
	{c: 40, r: 13, colour: 'blue', type:'final', pos: 4},
	{c: 68, r: 13, colour: 'white', type:'', pos: 10},
	{c: 4, r: 16, colour: 'white', type:'', pos: 25},
	{c: 68, r: 16, colour: 'white', type:'', pos: 11},
	{c: 4, r: 19, colour: 'white', type:'', pos: 24},
	{c: 32, r: 19, colour: 'green', type:'final', pos: 4},
	{c: 40, r: 19, colour: 'yellow', type:'final', pos: 4},
	{c: 68, r: 19, colour: 'white', type:'', pos: 12},
	{c: 27, r: 21, colour: 'green', type:'final', pos: 3},
	{c: 45, r: 21, colour: 'yellow', type:'final', pos: 3},
	{c: 4, r: 22, colour: 'green', type:'', pos: 23},
	{c: 68, r: 22, colour: 'yellow', type:'', pos: 13},
	{c: 22, r: 23, colour: 'green', type:'final', pos: 2},
	{c: 50, r: 23, colour: 'yellow', type:'final', pos: 2},
	{c: 10, r: 25, colour: 'green', type:'', pos: 22},
	{c: 17, r: 25, colour: 'green', type:'final', pos: 1},
	{c: 55, r: 25, colour: 'yellow', type:'final', pos: 1},
	{c: 62, r: 25, colour: 'yellow', type:'', pos: 14},
	{c: 0, r: 26, colour: 'green', type:'home', pos: 4},
	{c: 72, r: 26, colour: 'yellow', type:'home', pos: 1},
	{c: 4, r: 28, colour: 'green', type:'home', pos: 3},
	{c: 16, r: 28, colour: 'green', type:'', pos: 21},
	{c: 56, r: 28, colour: 'yellow', type:'', pos: 15},
	{c: 68, r: 28, colour: 'yellow', type:'home', pos: 2},
	{c: 8, r: 30, colour: 'green', type:'home', pos: 2},
	{c: 64, r: 30, colour: 'yellow', type:'home', pos: 3},
	{c: 22, r: 31, colour: 'green', type:'', pos: 20},
	{c: 29, r: 31, colour: 'white', type:'', pos: 19},
	{c: 36, r: 31, colour: 'white', type:'', pos: 18},
	{c: 43, r: 31, colour: 'white', type:'', pos: 17},
	{c: 50, r: 31, colour: 'yellow', type:'', pos: 16},
	{c: 12, r: 32, colour: 'green', type:'home', pos: 1},
	{c: 60, r: 32, colour: 'yellow', type:'home', pos: 4}
];

export {places};